### ISSUE TITLE
Spec is wrong, leading to spurious dialyzer warnings

### ISSUE THREAD

**Issue by samphilipd** [Voronchuk/elixir_google_spreadsheets#11]
https://github.com/Voronchuk/elixir_google_spreadsheets/blob/ba695f01219ffc3460fc1acbbb5f885b3c82255e/lib/elixir_google_spreadsheets/spreadsheet.ex#L153

The pattern {'ok', _result@1} can never match the type 'ok'

**Comment by Voronchuk** [comment]
Thanks for the notice, it's look like a bug left after we have implemented request queueing.

**Comment by Voronchuk** [comment]
Fixed in #13
