### ISSUE TITLE
Max rows

### ISSUE THREAD

**Issue by mbenatti** [Voronchuk/elixir_google_spreadsheets#22]
Why the max rows is 1000?
We can increase this value?

**Comment by Voronchuk** [comment]
I don't remember exact case for this restriction, but I guess there were some limitation I had to keep in mind. Surely single read batch for 1000+ rows is a bad idea, frankly I'm getting issues with 100+ rows if they are rich with data, but should be possible to paginate any amount of rows, so I'll check this.

**Comment by Voronchuk** [comment]
@mbenatti please use the latest master branch and check the new config option: `max_rows_per_request`, default batch amount was reduced to 301, but you can paginate anywhere with requests like `read_rows(pid, 1200, 1400)`.
