### ISSUE TITLE
Question - Check if a specific sheet exists and fallback to a default one

### ISSUE THREAD

**Issue by pdgonzalez872** [Voronchuk/elixir_google_spreadsheets#23]
Hi!

I'm using the library and it has been great so far! We started to make things a little more dynamic and I wanted to ask you if you suggest a particular strategy regarding trying to open a specific sheet, if the sheet doesn't exist, defaulting to a main one.

I've tried it a couple of ways, but it seems that I can't trap the error I keep getting when trying a sheet that may not exist. We kind of need to refer to it by name. Here is the error:

```
** (WithClauseError) no with clause matching: {:ok, %HTTPoison.Response{...}}
```

I tried matching against the error, `try/rescue`, `try/catch`, but I can't seem to make it work. I was wondering if you have solved an issue like this before.

Please let me know if you need more details about this and I'll provide them. Thanks!

**Comment by pdgonzalez872** [comment]
Update:
I was able to use `catch` and match against the error correctly.

I don't quite like this solution though, so my question still stands. Thanks for your time.

**Comment by Voronchuk** [comment]
Hi @pdgonzalez872 personally I'm getting `{:error, %GSS.GoogleApiError{message: "invalid google API status code 400"}}` with any request on an invalid list.

I have added a new `GSS.Spreadsheet.sheets(pid)` method, so you can make smth like that:

```
list_name = "missing"
{:ok, pid} = GSS.Spreadsheet.Supervisor.spreadsheet(spreadsheet_id, list_name: list_name)
sheets = GSS.Spreadsheet.sheets(pid)
{:ok, pid} =
  case Map.get(sheets, list_name) do
     nil ->
         GSS.Spreadsheet.Supervisor.spreadsheet(spreadsheet_id, list_name: "fallback")
     _ ->
        {:ok, pid}
  end
```

**Comment by pdgonzalez872** [comment]
Awesome! Thanks!
