### ISSUE TITLE
no process

### ISSUE THREAD

**Issue by mbenatti** [Voronchuk/elixir_google_spreadsheets#3]
I just tried to test the library:

My module:

`defmodule Test do`
`@moduledoc`
  `def sheet do`
   ` {:ok, pid} = GSS.Spreadsheet.Supervisor.spreadsheet("1bcsjIf1vzKiIaCf2CKS9mac4KU6eRtEnPbkPAOgKc2s")`
   ` id = GSS.Spreadsheet.id(pid)`
 `  IO.inspect id`
 ` end
end`

in iex -S mix:

`Test.sheet
** (exit) exited in: GenServer.call(GSS.Spreadsheet.Supervisor, {:start_child, ["1bcsjIf1vzKiIaCf2CKS9mac4KU6eRtEnPbkPAOgKc2s"]}, :infinity)
    ** (EXIT) no process
                        (elixir) lib/gen_server.ex:596: GenServer.call/3
    (elixir_google_spreadsheets) lib/elixir_google_spreadsheets/spreadsheet/supervisor.ex:16: GSS.Spreadsheet.Supervisor.spreadsheet/2
                   (test_sheets) lib/test_sheets/test.ex:4: Test.sheet/0
`

**Comment by Voronchuk** [comment]
Please, show your `mix.exs`

**Comment by belaustegui** [comment]
I'm having the same problem.

```elixir
iex(1)> {:ok, pid} = GSS.Spreadsheet.Supervisor.spreadsheet("xxx")
** (exit) exited in: GenServer.call(GSS.Spreadsheet.Supervisor, {:start_child, ["xxx"]}, :infinity)
    ** (EXIT) no process
    (elixir) lib/gen_server.ex:596: GenServer.call/3
             lib/elixir_google_spreadsheets/spreadsheet/supervisor.ex:16: GSS.Spreadsheet.Supervisor.spreadsheet/2
```

Looks like the GSS process is not being started properly. If I start it manually it works:

```elixir
iex(3)> GSS.start
{:ok, #PID<0.8996.0>}
iex(4)> {:ok, pid} = GSS.Spreadsheet.Supervisor.spreadsheet("xxx")
{:ok, #PID<0.9000.0>}
```

**Comment by Voronchuk** [comment]
Thanks for your feedback @belaustegui I'll take a look.

**Comment by Voronchuk** [comment]
Should be fixed in a Hex version.
