### ISSUE TITLE
Conflicting httpoison versions

### ISSUE THREAD

**Issue by Adzz** [Voronchuk/elixir_google_spreadsheets#32]
Can you do a release by any chance? I have this error when trying to use this lib:

```sh
Failed to use "httpoison" (version 1.5.0) because
  elixir_google_spreadsheets (versions 0.1.9 and 0.1.10) requires ~> 0.12
  mix.lock specifies 1.5.0
```

Looks like the fix is in master already.

Thanks!

**Comment by Voronchuk** [comment]
Hey, have you tried `0.1.10` is the issue in that version?

**Comment by Adzz** [comment]
Yes the issue is in there, I can see in releases it says:

> 3 commits to master since this release

![Screenshot 2019-03-18 at 09 18 00](https://user-images.githubusercontent.com/8428277/54519595-cc9b6400-495e-11e9-8792-d44f942f69d5.png)

The fix is one of those commits

**Comment by Voronchuk** [comment]
Upgrade to `0.1.11`, please

**Comment by Adzz** [comment]
Thank you!
