### ISSUE TITLE
Append multiple rows at once?

### ISSUE THREAD

**Issue by larskluge** [Voronchuk/elixir_google_spreadsheets#35]
Would a `GSS.Spreadsheet.append_rows` function be possible to append multiple rows with one API call?

Thanks!

**Comment by Voronchuk** [comment]
Should be possible in the scope of https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/append

I'll think about it.

**Comment by larskluge** [comment]
That would be amazing—I have tens of thousands of rows to append to multiple spreadsheets. I'm able to batch updates via `.update_rows` upto 50,000 rows per API call, would be great to have a similar way to append new rows. 

Thank you for your very helpful library.

**Comment by Voronchuk** [comment]
Please check **v0.1.12**

**Comment by larskluge** [comment]
Beautiful. Works well so far in a local test, will go into production the next days. Thank you!

**Comment by Voronchuk** [comment]
You are welcome
