### ISSUE TITLE
Question about release version

### ISSUE THREAD

**Issue by pdgonzalez872** [Voronchuk/elixir_google_spreadsheets#42]
The readme mentions `{:elixir_google_spreadsheets, "~> 0.1.15"}` , but it seems that the latest release was 0.1.14? Maybe I'm not looking at this correctly? Or maybe we just need a new release?

Thanks!

<img width="816" alt="Screen Shot 2020-01-03 at 07 51 36" src="https://user-images.githubusercontent.com/8906358/71726828-ec245000-2dfd-11ea-9e4a-800f940de239.png">

**Comment by Voronchuk** [comment]
https://hex.pm/packages/elixir_google_spreadsheets/0.1.15

I forgot to publish one on Github, sorry

**Comment by Voronchuk** [comment]
https://github.com/Voronchuk/elixir_google_spreadsheets/releases/tag/v0.1.15

**Comment by pdgonzalez872** [comment]
no worries! Thanks for the lib, I love it!
