### ISSUE TITLE
Feature to support sheets in the spreadsheet

### ISSUE THREAD

**Issue by gccoding** [Voronchuk/elixir_google_spreadsheets#5]
Great work! I was wondering you have any plans to extend this to support sheets inside a spreadsheet. I was looking for updating a cell in a sheet and I modified the code to do that. Here is the gist what I am talking about. https://gist.github.com/gccoding/573c7927651dc87f28bd15bba1f1ee76
Thanks.

**Comment by Voronchuk** [comment]
It's in plans, if you have pull request with the implementation it will be helpful.

**Comment by Voronchuk** [comment]
In #v0.1.2 you can now initialise your spreadsheet like: `{:ok, pid} = GSS.Spreadsheet.Supervisor.spreadsheet("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXX", list_name: "my_list3")` and work with it normally in scope of that list.
